### ISSUE TITLE
not an issue - feature request 

### ISSUE THREAD

**Issue by art3mHQ** [feimosi/baguetteBox.js#194]
Thanks a lot for baguetteBox.js it's lovely!

It would be really sweet if you consider possibility of adding an Option for changing animation time (for example to slowdown 'fadeIn').

Cheers! Thank u one more time!!

**Comment by feimosi** [comment]
Thanks, I'm glad you like it!

Actually, you can override the animation yourself. Currently it's:

```css
#baguetteBox-slider {
    transition: left .4s ease, transform .4s ease;
}
```
